app:
  name: "%project.artifactId%"
  message: "Hello from ${app.name}"
  remember-me:
    key: ${RM_KEY:spring-test}
    ttl: ${RM_TTL:30d}

loki:
  url: ${LOKI_URL:http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push}

pclib:
  db:
    enabled: true
    expose-database: true
    expose-connector: true
    auto-create: true

    postgres:
      protocol: "postgres"
      name: "spring_test_postgres"
      username: "${DB_USER}"
      password: "${DB_PASS}"
      host: "${DB_HOST:localhost}"
      port: "${DB_PORT:5432}"

spring:
  application:
    name: "%project.artifactId%"
#    version: "%project.version%"
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms

  session:
    store-type: redis
    timeout: 12h
    redis:
      namespace: "${app.name}:session"
      flush-mode: on-save

  cache:
    type: redis
    redis:
      key-prefix: "${app.name}:cache:"
      time-to-live: 30m
      use-key-prefix: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: ${app.name}-session
        http-only: true
        same-site: lax
        secure: false
    remember-me:
      cookie:
        name: ${app.name}-uid

management:
  server:
    port: 8081

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    lu.kbra: DEBUG