app:
  name: ${APP_NAME:spring-test}
  message: "Hello from ${app.name}"

pclib:
  db:
    enabled: true
    expose-database: true
    expose-connector: true
    auto-create: true
    protocol: "mysql"

    mysql:
      name: "spring_test_mysql"
      username: "user"
      password: "pass"

spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms

  session:
    store-type: redis
    timeout: 12h
    redis:
      namespace: "${app.name}:session"
      flush-mode: on-save

  cache:
    type: redis
    redis:
      key-prefix: "${app.name}:cache:"
      time-to-live: 30m
      use-key-prefix: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: ${app.name}-session
        http-only: true
        same-site: lax
        secure: false

logging:
  level:
    root: INFO
    lu.kbra: DEBUG